version: '3.8'

services:

  db:
    container_name: db
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.postres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  app:
    depends_on:
      - db
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?schema=public
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  postgres:
