name: run unit tests
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repo code
        uses: actions/checkout@4
      - name: install depend
        run: npm ci
      - name: run unit tests
        run: npm run test:unit
      
